### ISSUE TITLE
User Analysis Tool

### ISSUE THREAD

**Issue by MYank0** [hasadna/open-bus#47]
**The need** - We were approached by Tony Weisbuch to create an app which will allow citizen to analyze by themselves transport data, specifically regarding Public Transit in the Suburbs. See Mr. Weisbuch full email [here](https://drive.google.com/file/d/0ByIrzj3OFMnIWVJiOUR4akktMXc/view).
Before creating an app or UI we need to think what are the capabilities/ services we want to provide in such tool.
Here are some Possible analysis tools/ queries:

1. Public Transport from and to a certain area - what buses serve the area? In what frequency? Where can you get by using a bus? (one bus? exchanges?)
2. Public transport between two areas - What buses can you take? How long will it take you? Frequency?
3. Bus2Train - combine queries from bus2Train research and use them for specific areas and lines?
4. Specific lines analysis?

These are only initial ideas and this issue's purpose is to create a discussion what kind of tools we can give to the public.

Write down all idea and comments which come up  :bulb:

**Comment by zvigrauer** [comment]
My gut feeling is that we have here two distinct audiences, that may be
best served in different ways. One is the citizen that wants to take a bus
from one point to another. The other is the researcher (I am grouping here
lots of different people, obviously, with diverse interests) that want to
know if one line or one area is served better than another, when the delays
are, etc. with a goal of optimizing the system).

The first need an immediate answer, probably through an app. I know what I
usually need - compare a couple of buses expected arrival times at one or
two stations. I know which buses take me to my destinations, and which
stations the leave from, but I don't know which will come first.

The second want to start a study, perhaps one that looks at many lines,
buses, stations, over a long period - you need a long time for getting
(statistically) meaningful results otherwise your results will vary from
one query to the next - and need also incorporate experiment design
framework (randomization, matching of days/hours/seasons, and so on in an
efficient way). For example - which bus is better TA to Jerusalem, 405 or
480, or is the service to Rahat worse than that for Lehavim, etc. (bad
example, I think, both have the same station but who knows.

For the first, I'd use an app similar to existing ones (Kol Kav, Moovit)
but simpler, with simple UI and more control over queries. For the second,
I'd use a web page with many options (type of study, duration,
days/hours/seasons, experimental design, bus(es), station(s), areas to
compare), and the user will have to bring his own permission to access the
MOT server and a place to store the resulting data, otherwise we'll empower
people to attack the infrastructure we and MOT use.

Just my 2 cents.

Z.

**Comment by daphshez** [comment]
Thanks @MYank0 for opening this discussion and @zvigrauer for your very relevant comments. 

I think I should elaborate a bit on the background for this discussion. Here's a high level view of what we are trying to build: 

![state of the open bus](https://user-images.githubusercontent.com/250509/28492215-fb9c826e-6ef6-11e7-9419-2787d1f10b22.png)

We are currently pretty confident about building the PT archive.

The question is what we are going to do once this archive is available (say by the end of the year?). What are those "applications" on the right side of the diagram? 

I agree with @zvigrauer that this depends on what users we plan to serve. I don't think it's our job to serve end users (there are commercial solutions for that). I think we should focus on "researchers" -
 journalists, activists (people working to improve transport in their own environment, or organisations like 15 minutes), regulators, academics, even the operators or people tendering to operate lines. 

Some of these people would only need database access and would do the rest of the work themselves. For some we might want to create tailored reports ourselves. 

But there might also be also a space for a web UI allowing people with no huge data analysis background to analyse certain questions. 

The next question would be what should be included in that interface, so it's useful, easy to use , and wouldn't take us years to build... Tony's email that Michal posted gives us one possible use case. 

What I'd be happy to know is - what do people think about this use case? What other use cases are important? Or maybe people disagree with any of the assumptions I made?

**Comment by daphshez** [comment]
Here's some extra ideas from Tony, sorry for the RTL going all wrong as usual: 

אני מבקש מכם לשקול בניית מעין מפת תחבורה ציבורית ויזואלית שתדרג את האיזורים, ערים, שכונות לפי איכות שירותי תח״צ (אפשר לעשות זאת בעזרת צבעים). בעזרת ממפת תח״צ ויזואלית מסוג זה, יהיה ניתן להבחין בקלות ובמהירות את ההבדלים באיכות שירותי תח״צ שניתנים באיזורים, ערים ושכונות שונות ברחבי הארץ.
במציאות הרגולטורית העכשיוית, לרשויות המקומיות יש מעמד סטטוטורי בתכנון התח״צ במרחב השיפוט שלהן. לכן, שירותי התח״צ מושפעים בעיקר מהרצון ומהיכולת של הרשויות המקומיות לקדם את התח״צ באיזור השיפוט שלהן. ככל שרשות מקומית חזקה ומקושרת יותר (בעיקר פוליטית, בסדרונות השילטון), כך גם התח״צ באיזור השיפוט שלהן איכותית יותר.
אם נחזור לעניין הסובסידה (דרך אגב סובסידיה בתח״צ כ- 6 מיליארד ש״ח), איכות התח״צ גדלה ביחס פרופורציונאלי לגובה הסובסידיה שרשות מקומית מצליחה להשיג - ולכן לכח הרשות המקומית במסדרונות השלטון יש השפעה גדולה מאוד על איכות שירותי הת״צ באיזור השיפוט שלה. 
מפת תח״צ ויזואלית שתדרג את איכות שירותי התח״צ באזורים, ערים ושכונות = כלי שיעזור לאזרחים מן השורה להבחין בהבדלים ולעשות שינוי באזור מגוריהם.

**Comment by open-bus-israel** [comment]
in general, I agree with the points Ziv is making.

As we discussed at the hackathon, we have two distinct use-cases in mind:
- Getting help with planning a route when you want to ride a bus
- Getting insights about service quality.

The former is probably more aimed at a consumer, the latter - at policy 
makers, journalists, and activists.

My gut feeling is that for the route-planning scenario, investing in a 
full-blown consumer application, such as an app, might not be the best use 
of our time. 
It is a very complex task and quite a few app developers are already 
investing a lot of resources into this. A more cost-effective approach 
might be to just to give these apps access to our more-accurate data (maybe 
by exposing an API or by other means).

The area where we could provide unique value might be in producing reports 
and building tools that can help policy makers (or pressure them) to 
evaluate and hopefully improve the service.

At the hackathon we started sketching a possible design for a report, 
you're invited to take look and give feedback here:
https://realtimeboard.com/app/board/o9J_k0HD7gg=/

**Comment by open-bus-israel** [comment]
Oren,

Here are my needs...

1. Select a station or two, find expected real time arrival data for buses
(could be all buses, or a choice of which buses).

I usually know which buses I can take to get from A to B, and the choice
depends on when the next bus and the one after that will arrive. So I'll
check the 142 station and the 25/18/125 station to see which will get in
faster. This MAY be possible in Moovit, but their algorithm makes choices
for me, and if their selection is not right, you are stumped.

KolKav allows one to do it, but only one station at a time. If one can
check several stations at once, might be nice. Also, until recently, KolKav
was really slow and unresponsive. Now it seems to be okay.

Sometimes I am at a station and want to find out which buses arrive when. A
variation on the previous one, so if I see the next bus arrives in 20 min,
I can get a sandwich, or find another line (the difference is that I don't
know the number or location of another station).

2. Something general on bus lines - which buses are prone to be late, at
what time (e.g. bus 63 at certain times of day due to traffic jams). Which
buses simple fail to leave at all (#23 from Carmelit terminal), etc. Some
of this you have on your bus.

This will require compilation of data on buses.

3. Research reports, like you suggest.

Z.

**Comment by sagiben** [comment]
Hi,

Regarding : "Getting help with planning a route when you want to ride a bus"

There's an well known and very live opensource project called
OpenTripPlanner (http://www.opentripplanner.org/otp/)
Movit in there previous name used to use this project for their trip
planner (look for the name Tranzmate at the followng page :
http://docs.opentripplanner.org/en/latest/Deployments/)
An Israeli society named Hamakor (עמותת "המקור") had a live server for this
project for couple of month but it was shut down due to funding issues.
You can read about the project in the following blog post :
https://yehudab.com/blog/2012/05/otp-il-temp-server/


Sagi.

**Comment by tonyweiss** [comment]
שלום לכולם
אני מחדד את נושא בניית מפת תחבורה ציבורית

טוני
[bniat-mapa_1.pdf](https://github.com/hasadna/open-bus/files/1185593/bniat-mapa_1.pdf)
![tzir-zman1](https://user-images.githubusercontent.com/30567974/28752440-fb6134de-7527-11e7-9653-4b54e8ebc634.png)
