### ISSUE TITLE
Write web page that display a sql query 

### ISSUE THREAD

**Issue by AvivSela** [hasadna/open-bus#69]
write a web page that display a data from sql query.

- create csv file that will represent the result of sql query.
- write a static web page that show the data in a table.

**Definition Of Done**
- A web page that shows the csv file in a table.

**Comment by cjer** [comment]
I'll do this initial thing using [Pelican](https://github.com/getpelican/pelican) since I know it reasonabely well. 

Some useful plugins I found:
1. https://github.com/jessaustin/pelican-json-reader
1. https://github.com/e9t/pelican-loadcsv
1. https://github.com/getpelican/pelican-plugins/tree/master/tipue_search
1. This could have been nice... we could try Jekyll or Nikola instead but I never used them...

**Comment by cjer** [comment]
About the server, we could use Github Pages on this repository if its possible, otherwise we'll need to setup some other simple web server to handle the requests to the static pages generated by Pelican.

**Comment by cjer** [comment]
Initial code for pelican site is here. Waiting for @uda for a repository for hosting it as a GitHub page, and a domain under hasadna.

**Comment by cjer** [comment]
Closing for now, not relevant at the moment
